title = Hello World
package.name = helloworld
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
source.include_patterns = assets/*,images/*.png
version = 0.1
requirements = kivy
orientation = portrait
fullscreen = 0
android.permissions = INTERNET
log_level = 2
source.icon.filename = %(source.dir)s/data/icon.png
orientation = portrait
