# Use an official Python runtime as a parent image

FROM python:3.8-slim

# Set the working directory in the container

WORKDIR /testwork
COPY acesec.py /testwork/
# Run the Python script when the container launches

ENTRYPOINT ["python", "/testwork/acesec.py"]
