pipeline {

    agent any

    environment {

        EC2_HOST = '51.20.80.177 '

        EC2_USER = 'ubuntu'

    }

    stage('Clean Workspace') {
    steps {
        deleteDir() // Clean workspace
    }
}


    stages {

        stage('Build') {

            steps {

                dir('Exercise28') {

                    sh 'ls'

                    sh 'docker build -t asedes -f Dockerfile .'

                }

            }

        }

 

        stage('Push to Docker Hub') {

            steps {

                sh "docker login -u rama987 -p Dorasala@123devi"

                sh 'docker tag flask rama987/rama:asedes'

                sh "docker push rama987/rama:asedes"

            }

        }

 

        stage('Pull Docker Image on EC2') {

            steps {

                script {

                    withCredentials([file(credentialsId: 'rama', variable: 'PRIVATE_KEY_FILE')]) {

                        sh """

                            chmod 400 \$PRIVATE_KEY_FILE

                            ssh -i \$PRIVATE_KEY_FILE -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \$EC2_USER@\$EC2_HOST<< EOF

                            
 

                            sudo docker login -u rama987/rama -p 'Dorasala@123devi'

                            sudo docker pull rama987/rama:asedes

                            sudo docker run -d -p 5000:5000 --name xmltodict-app rama987/rama:asedes


                        """

                    }

                }

            }

        }

    }

}
