pipeline {

    agent any

    environment {

        EC2_HOST = '13.48.104.196'

        EC2_USER = 'ubuntu'

    }

    stages {

        stage('Build') {

            steps {

                dir('Exercise2') {

                    sh 'ls'

                    sh 'docker build -t server -f server_Dockerfile .'

                    

                }

            }

        }

 

        stage('Push to Docker Hub') {

            steps {

                sh "docker login -u rama987 -p Dorasala@123devi"

                sh 'docker tag flask rama987/rama:server'

                sh "docker push rama987/rama:server"

            }

        }

 

        stage('Pull Docker Image on EC2') {

            steps {

                script {

                    withCredentials([file(credentialsId: 'rama', variable: 'PRIVATE_KEY_FILE')]) {

                        sh """

                            chmod 400 \$PRIVATE_KEY_FILE

                            ssh -i \$PRIVATE_KEY_FILE -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \$EC2_USER@\$EC2_HOST<< EOF

                            
 

                            sudo docker login -u rama987/rama -p 'Dorasala@123devi'

                            sudo docker pull rama987/rama:server

                            sudo docker run -d -p 5000:5000 --name server-app rama987/rama:server


                        """

                    }

                }

            }

        }

    }

}
